-- exam
CREATE TABLE dept03 (
                     deptno NUMBER(3),
                     dname VARCHAR2(7)
                     )
COMMENT ON TABLE dept03 IS '부서';
COMMENT ON COLUMN dept03.deptno IS '부서번호';
COMMENT ON COLUMN dept03.dname IS '부서명';

ALTER TABLE DEPT03 ADD(area VARCHAR2(20));
COMMENT ON COLUMN dept03.area IS '지역';

ALTER TABLE DEPT03 MODIFY DNAME VARCHAR2(20);

ALTER TABLE DEPT03 ADD CONSTRAINT PK_DEPTNO PRIMARY KEY(deptno);

CREATE TABLE emp03 (
                    empno VARCHAR2(4) CONSTRAINT PK_ENPNO PRIMARY KEY,
                    name VARCHAR2(20),
                    deptno VARCHAR2(3)CONSTRAINT NOTNULL CHECK(deptno IS NOT NULL),
                    pempno VARCHAR2(4),
                    pay NUMBER CONSTRAINT NOTNULL2 CHECK(pay IS NOT NULL),
                    position VARCHAR2(20),
                    regdate VARCHAR2(20)
                   );
COMMENT ON TABLE EMP03 IS '사원';
COMMENT ON COLUMN EMP03.EMPNO IS '사원코드';
COMMENT ON COLUMN EMP03.NAME IS '사원이름';
COMMENT ON COLUMN EMP03.DEPTNO IS '부서코드';
COMMENT ON COLUMN EMP03.PEMPNO IS '상사코드';
COMMENT ON COLUMN EMP03.PAY IS '급여';
COMMENT ON COLUMN EMP03.POSITION IS '직급';
COMMENT ON COLUMN EMP03.REGDATE IS '등록일';
COMMIT;

INSERT INTO dept03
VALUES(101, '영업부', NULL);
INSERT INTO dept03
VALUES(102, '총무부', NULL);
INSERT INTO dept03
VALUES(103, '기획부', NULL);
INSERT INTO dept03
VALUES(104, '홍보부', NULL);

CREATE SEQUENCE SEQ_EMP03_EMPNO
INCREMENT BY 1
START WITH 1001;

INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '가가가', 101, NULL, 450, '부장', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '나나나', 102, NULL, 400, '부장', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '다다다', 101, 1001, 350, '과장', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '라라라', 103, NULL, 410, '과장', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '마마마', 101, 1003, 300, '대리', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '바바바', 103, 1004, 400, '대리', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '가나다', 102, 1002, 320, '대리', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '홍길동', 102, 1007, 380, '사원', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '강감찬', 103, 1006, 250, '사원', SYSDATE);
INSERT INTO EMP03
VALUES(SEQ_EMP03_EMPNO.NEXTVAL, '이순신', 101, 1005, 200, '사원', SYSDATE);

COMMIT;

UPDATE DEPT03
SET
    AREA = '서울'
WHERE DNAME = '영업부';
UPDATE DEPT03
SET
    AREA = '부산'
WHERE DNAME <> '영업부';
COMMIT;

DELETE FROM EMP03
WHERE DEPTNO = 101;
ROLLBACK;

SELECT NAME, POSITION
FROM EMP03
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT03 WHERE DNAME = '영업부' OR DNAME = '총무부')
ORDER BY EMPNO
;

SELECT DEPTNO, ROUND(AVG(PAY)) AS 급여평균, COUNT(NAME) AS 인원수
FROM EMP03
GROUP BY DEPTNO;